var eigo = [
    n5v = [
        "to meet",
        "blue",
        "blue",
        "red",
        "red",
        "bright",
        "autumn",
        "to open,to become open",
        "to open",
        "to give",
        "morning",
        "breakfast",
        "day after tomorrow",
        "foot,leg",
        "tomorrow",
        "over there",
        "to play,to make a visit",
        "warm",
        "head",
        "new",
        "there",
        "hot",
        "hot to the touch",
        "kind, deep, thick",
        "over there",
        "afterwards",
        "you",
        "(humble) older brother",
        "(humble) older sister",
        "that over there",
        "um...",
        "apartment",
        "to bathe,to shower",
        "dangerous",
        "sweet",
        "not very",
        "rain",
        "candy",
        "to wash",
        "to be,to have (used for inanimate objects)",
        "to walk",
        "that",
        "good",
        "no",
        "to say",
        "house",
        "how",
        "to go",
        "how many?,how old?",
        "how much?",
        "pond",
        "medical doctor",
        "chair",
        "busy,irritated",
        "painful",
        "one",
        "(1) one day, (2) first of month",
        "best,first",
        "when",
        "five days, fifth day",
        "together",
        "five",
        "always",
        "dog",
        "now",
        "meaning",
        "(humble) younger sister",
        "unpleasant",
        "entrance",
        "to be, to have (used for people and animals)",
        "to need",
        "to put in",
        "colour",
        "various",
        "on top of",
        "behind",
        "thin,weak",
        "song",
        "to sing",
        "to be born",
        "sea",
        "to sell",
        "noisy,annoying",
        "jacket",
        "picture",
        "movie",
        "cinema",
        "English language",
        "yes",
        "station",
        "elevator",
        "pencil",
        "delicious",
        "many",
        "big",
        "big",
        "great number of people",
        "(honorable) mother",
        "sweets, candy",
        "money",
        "to get up",
        "to put",
        "(honorable) wife",
        "alcohol, rice wine",
        "plate, dish",
        "grandfather,male senior citizen",
        "to teach,to tell",
        "uncle,middle aged gentleman",
        "to push, to stamp something",
        "late,slow",
        "green tea",
        "bathroom",
        "(honorable) father",
        "younger brother",
        "man",
        "boy",
        "day before yesterday",
        "year before last",
        "adult",
        "stomach",
        "same",
        "(honorable) older brother",
        "(honorable) older sister",
        "grandmother,female senior-citizen",
        "aunt",
        "bath",
        "boxed lunch",
        "to remember",
        "friendly term for policeman",
        "heavy",
        "interesting",
        "to swim",
        "to get off, to descend",
        "to finish",
        "music",
        "woman",
        "girl",
        "foreign country",
        "foreigner",
        "company",
        "stairs",
        "shopping",
        "to buy",
        "to return something",
        "to go back",
        "to take time or money",
        "key",
        "to write",
        "student",
        "to call by phone",
        "umbrella",
        "to lend",
        "wind",
        "a cold",
        "family",
        "person, way of doing",
        "school",
        "cup",
        "household",
        "a corner",
        "bag,basket",
        "a vase",
        "paper",
        "camera",
        "Tuesday",
        "spicy",
        "body",
        "to borrow",
        "light",
        "curry",
        "calendar",
        "river",
        "cute",
        "Chinese character",
        "tree,wood",
        "yellow",
        "yellow",
        "to disappear",
        "to hear,to listen to,to ask",
        "north",
        "guitar",
        "dirty",
        "coffee lounge",
        "postage stamp",
        "ticket",
        "yesterday",
        "nine",
        "beef",
        "milk",
        "today",
        "classroom",
        "(humble) siblings",
        "last year",
        "hate",
        "to cut",
        "to put on from the shoulders down",
        "pretty,clean",
        "kilogram",
        "kilometre",
        "bank",
        "Friday",
        "medicine",
        "please",
        "fruit",
        "mouth,opening",
        "shoes",
        "socks",
        "country",
        "cloudy weather",
        "to become cloudy,to become dim",
        "gloomy",
        "class",
        "gram",
        "to come",
        "car,vehicle",
        "black",
        "black",
        "policeman",
        "this morning",
        "to erase,to turn off power",
        "splendid,enough",
        "marriage",
        "Monday",
        "entry hall",
        "health, vitality",
        "five",
        "park",
        "intersection",
        "black tea",
        "police box",
        "voice",
        "coat,tennis court",
        "coffee",
        "here",
        "afternoon",
        "nine days, ninth day",
        "nine",
        "morning",
        "to answer",
        "this person or way",
        "this person or way",
        "a glass",
        "this year",
        "word,language",
        "child",
        "this",
        "cooked rice,meal",
        "to copy",
        "to be worried",
        "this",
        "this month",
        "this week",
        "such",
        "this evening",
        "well…",
        "wallet",
        "fish",
        "the future,previous",
        "to bloom",
        "composition,writing",
        "to stretch out hands,to raise an umbrella",
        "magazine",
        "sugar",
        "cold",
        "year after next",
        "three",
        "to stroll",
        "four",
        "salt",
        "however",
        "time",
        "job",
        "dictionary",
        "quiet",
        "below",
        "seven",
        "question",
        "bicycle",
        "automobile",
        "to die",
        "dictionary",
        "oneself",
        "to close,to be closed",
        "to close something",
        "to tie",
        "well then…",
        "photograph",
        "shirt",
        "shower",
        "ten",
        "lesson,class work",
        "homework",
        "skillful",
        "strong,durable",
        "soy sauce",
        "dining hall",
        "to know",
        "white",
        "white",
        "newspaper",
        "Wednesday",
        "to smoke,to suck",
        "skirt",
        "likeable",
        "a few",
        "instantly",
        "few",
        "refreshing",
        "heater",
        "spoon",
        "sport",
        "trousers",
        "to live in",
        "slippers",
        "to do",
        "to sit",
        "height,stature",
        "pupil",
        "sweater,jumper",
        "soap",
        "business suit",
        "narrow",
        "zero",
        "thousand",
        "last month",
        "last week",
        "teacher,doctor",
        "washing",
        "all",
        "to clean, to sweep",
        "and",
        "that place",
        "over there",
        "over there",
        "outside",
        "that",
        "near,beside",
        "sky",
        "that",
        "after that",
        "in that situation",
        "university",
        "embassy",
        "all right",
        "to be very likeable",
        "important",
        "kitchen",
        "very",
        "difficult situation",
        "tall, expensive",
        "many",
        "taxi",
        "to put out",
        "to stand",
        "length,height",
        "building",
        "enjoyable",
        "to ask",
        "tobacco,cigarettes",
        "probably",
        "food",
        "to eat",
        "egg",
        "who",
        "somebody",
        "birthday",
        "gradually",
        "little",
        "little",
        "near",
        "to differ",
        "near",
        "underground train",
        "map",
        "brown",
        "rice bowl",
        "exactly",
        "somewhat",
        "first of month",
        "to use",
        "to get tired",
        "next",
        "to arrive at",
        "desk",
        "to make",
        "to turn on",
        "to work for someone",
        "boring",
        "cold to the touch",
        "powerful",
        "hand",
        "tape",
        "table",
        "tape recorder",
        "to go out",
        "letter",
        "to be able to",
        "exit",
        "test",
        "with that...",
        "department store",
        "but",
        "to appear,to leave",
        "television",
        "weather",
        "electricity,electric light",
        "electric train",
        "telephone",
        "Japanese style door",
        "Western style door",
        "toilet",
        "how,in what way",
        "for what reason",
        "please",
        "animal",
        "thanks",
        "far",
        "ten days,the tenth day",
        "sometimes",
        "watch,clock",
        "where",
        "place",
        "year",
        "library",
        "which of two",
        "which",
        "very",
        "who",
        "next door to",
        "which",
        "to fly,to hop",
        "to come to a halt",
        "friend",
        "Saturday",
        "bird",
        "chicken meat",
        "to take something",
        "to take a photo or record a film",
        "which (of three or more)",
        "knife",
        "middle",
        "long",
        "animal noise. to chirp, roar or croak etc.",
        "to lose something",
        "why",
        "summer",
        "summer holiday",
        "et cetera",
        "seven",
        "seven days,the seventh day",
        "name",
        "to learn",
        "to line up,to stand in a line",
        "to line up,to set up",
        "to become",
        "what",
        "two",
        "bustling,busy",
        "meat",
        "west",
        "Sunday",
        "luggage",
        "news",
        "garden",
        "to take off clothes",
        "luke warm",
        "tie,necktie",
        "cat",
        "to go to bed,to sleep",
        "notebook,exercise book",
        "to climb",
        "a drink",
        "to drink",
        "to get on,to ride",
        "tooth",
        "party",
        "yes",
        "ashtray",
        "to enter,to contain",
        "postcard",
        "to wear,to put on trousers",
        "box",
        "bridge",
        "chopsticks",
        "to begin",
        "beginning",
        "for the first time",
        "to run",
        "bus",
        "butter",
        "20 years old,20th year",
        "to work",
        "eight",
        "twenty days,twentieth",
        "flower",
        "nose",
        "talk,story",
        "to speak",
        "early",
        "quick",
        "spring",
        "to stick",
        "clear weather",
        "to be sunny",
        "half",
        "evening",
        "bread",
        "handkerchief",
        "number",
        "evening meal",
        "half minute",
        "east",
        "to pull",
        "to play an instrument with strings, including piano",
        "short,low",
        "aeroplane",
        "left hand side",
        "person",
        "one",
        "one month",
        "one person",
        "free time",
        "hundred",
        "hospital",
        "illness",
        "noon, daytime",
        "midday meal",
        "spacious,wide",
        "roll of film",
        "envelope",
        "swimming pool",
        "fork",
        "to blow",
        "clothes",
        "two",
        "pork",
        "two people",
        "two days, second day of the month",
        "fat",
        "winter",
        "to fall, e.g. rain or snow",
        "old (not used for people)",
        "bath",
        "sentence,text",
        "page",
        "unskillful",
        "bed",
        "pet",
        "room",
        "area",
        "pen",
        "to study",
        "useful, convenient",
        "hat",
        "ball-point pen",
        "other, the rest",
        "pocket",
        "want",
        "post",
        "thin",
        "button",
        "hotel",
        "book",
        "bookshelves",
        "truth",
        "every morning",
        "every month",
        "every week",
        "every day",
        "every year",
        "every night",
        "before",
        "to turn,to bend",
        "unpleasant",
        "again,and",
        "yet,still",
        "town,city",
        "to wait",
        "straight ahead,direct",
        "match",
        "window",
        "round,circular",
        "ten thousand",
        "fountain pen",
        "to brush teeth, to polish",
        "right side",
        "short",
        "water",
        "shop",
        "to show",
        "street",
        "three days, third day of the month",
        "three",
        "green",
        "everyone",
        "south",
        "ear",
        "to see, to watch",
        "everyone",
        "six days, sixth day of the month",
        "over there",
        "difficult",
        "six",
        "village",
        "eye",
        "metre",
        "glasses",
        "already",
        "again",
        "Thursday",
        "to hold",
        "more",
        "thing",
        "gate",
        "problem",
        "greengrocer",
        "vegetable",
        "easy, simple",
        "cheap",
        "rest,holiday",
        "to rest",
        "eight",
        "mountain",
        "to do",
        "evening",
        "dinner",
        "post office",
        "last night",
        "famous",
        "snow",
        "to go",
        "slowly",
        "eight days, eighth day of the month",
        "western-style clothes",
        "often, well",
        "beside,side,width",
        "four days, fouth day of the month",
        "four",
        "to call out,to invite",
        "to read",
        "evening,night",
        "weak",
        "next month",
        "next week",
        "next year",
        "radio",
        "radio cassette player",
        "splendid",
        "overseas student",
        "both parents",
        "cuisine",
        "travel",
        "zero",
        "refrigerator",
        "record",
        "restaurant",
        "to practice",
        "corridor",
        "six",
        "business shirt",
        "young",
        "to be understood",
        "to forget",
        "(humble) I,myself",
        "I,myself",
        "to hand over",
        "to go across",
        "bad",
        "Used for comparison.",
        ],
    n4v = [],
    n3v = [],
    n2v = [],
    n1v = [],
    list = []    
];

var hiragana = [
    n5v = [
        "あう",
        "あお",
        "あおい",
        "あか",
        "あかい",
        "あかるい",
        "あき",
        "あく",
        "あける",
        "あげる",
        "あさ",
        "あさごはん",
        "あさって",
        "あし",
        "あした",
        "あそこ",
        "あそぶ",
        "あたたかい",
        "あたま",
        "あたらしい",
        "あちら",
        "あつい",
        "あつい",
        "あつい",
        "あっち",
        "あと",
        "あなた",
        "あに",
        "あね",
        "あの",
        "あの",
        "アパート",
        "あびる",
        "あぶない",
        "あまい",
        "あまり",
        "あめ",
        "あめ",
        "あらう",
        "ある",
        "あるく",
        "あれ",
        "いい/よい",
        "いいえ",
        "いう",
        "いえ",
        "いかが",
        "いく",
        "いくつ",
        "いくら",
        "いけ",
        "いしゃ",
        "いす",
        "いそがしい",
        "いたい",
        "いち",
        "いちにち",
        "いちばん",
        "いつ",
        "いつか",
        "いっしょ",
        "いつつ",
        "いつも",
        "いぬ",
        "いま",
        "いみ",
        "いもうと",
        "いや",
        "いりぐち",
        "いる",
        "いる",
        "いれる",
        "いろ",
        "いろいろ",
        "うえ",
        "うしろ",
        "うすい",
        "うた",
        "うたう",
        "うまれる",
        "うみ",
        "うる",
        "うるさい",
        "うわぎ",
        "え",
        "えいが",
        "えいがかん",
        "えいご",
        "ええ",
        "えき",
        "エレベーター",
        "えんぴつ",
        "おいしい",
        "おおい",
        "おおきい",
        "おおきな",
        "おおぜい",
        "おかあさん",
        "おかし",
        "おかね",
        "おきる",
        "おく",
        "おくさん",
        "おさけ",
        "おさら",
        "おじいさん",
        "おしえる",
        "おじさん",
        "おす",
        "おそい",
        "おちゃ",
        "おてあらい",
        "おとうさん",
        "おとうと",
        "おとこ",
        "おとこのこ",
        "おととい",
        "おととし",
        "おとな",
        "おなか",
        "おなじ",
        "おにいさん",
        "おねえさん",
        "おばあさん",
        "おばさん",
        "おふろ",
        "おべんとう",
        "おぼえる",
        "おまわりさん",
        "おもい",
        "おもしろい",
        "およぐ",
        "おりる",
        "おわる",
        "おんがく",
        "おんな",
        "おんなのこ",
        "がいこく",
        "がいこくじん",
        "かいしゃ",
        "かいだん",
        "かいもの",
        "かう",
        "かえす",
        "かえる",
        "かかる",
        "かぎ",
        "かく",
        "がくせい",
        "かける",
        "かさ",
        "かす",
        "かぜ",
        "かぜ",
        "かぞく",
        "かた",
        "がっこう",
        "カップ",
        "かてい",
        "かど",
        "かばん",
        "かびん",
        "かみ",
        "カメラ",
        "かようび",
        "からい",
        "からだ",
        "かりる",
        "かるい",
        "カレー",
        "カレンダー",
        "かわ",
        "かわいい",
        "かんじ",
        "き",
        "きいろ",
        "きいろい",
        "きえる",
        "きく",
        "きた",
        "ギター",
        "きたない",
        "きっさてん",
        "きって",
        "きっぷ",
        "きのう",
        "きゅう / く",
        "ぎゅうにく",
        "ぎゅうにゅう",
        "きょう",
        "きょうしつ",
        "きょうだい",
        "きょねん",
        "きらい",
        "きる",
        "きる",
        "きれい",
        "キロ/キログラム",
        "キロ/キロメートル",
        "ぎんこう",
        "きんようび",
        "くすり",
        "ください",
        "くだもの",
        "くち",
        "くつ",
        "くつした",
        "くに",
        "くもり",
        "くもる",
        "くらい",
        "クラス",
        "グラム",
        "くる",
        "くるま",
        "くろ",
        "くろい",
        "けいかん",
        "けさ",
        "けす",
        "けっこう",
        "けっこん",
        "げつようび",
        "げんかん",
        "げんき",
        "ご",
        "こうえん",
        "こうさてん",
        "こうちゃ",
        "こうばん",
        "こえ",
        "コート",
        "コーヒー",
        "ここ",
        "ごご",
        "ここのか",
        "ここのつ",
        "ごぜん",
        "こたえる",
        "こちら",
        "こっち",
        "コップ",
        "ことし",
        "ことば",
        "こども",
        "この",
        "ごはん",
        "コピーする",
        "こまる",
        "これ",
        "こんげつ",
        "こんしゅう",
        "こんな",
        "こんばん",
        "さあ",
        "さいふ",
        "さかな",
        "さき",
        "さく",
        "さくぶん",
        "さす",
        "ざっし",
        "さとう",
        "さむい",
        "さらいねん",
        "さん",
        "さんぽする",
        "し / よん",
        "しお",
        "しかし",
        "じかん",
        "しごと",
        "じしょ",
        "しずか",
        "した",
        "しち / なな",
        "しつもん",
        "じてんしゃ",
        "じどうしゃ",
        "しぬ",
        "じびき",
        "じぶん",
        "しまる",
        "しめる",
        "しめる",
        "じゃ/じゃあ",
        "しゃしん",
        "シャツ",
        "シャワー",
        "じゅう とお",
        "じゅぎょう",
        "しゅくだい",
        "じょうず",
        "じょうぶ",
        "しょうゆ",
        "しょくどう",
        "しる",
        "しろ",
        "しろい",
        "しんぶん",
        "すいようび",
        "すう",
        "スカート",
        "すき",
        "すくない",
        "すぐに",
        "すこし",
        "すずしい",
        "ストーブ",
        "スプーン",
        "スポーツ",
        "ズボン",
        "すむ",
        "スリッパ",
        "する",
        "すわる",
        "せ",
        "せいと",
        "セーター",
        "せっけん",
        "せびろ",
        "せまい",
        "ゼロ",
        "せん",
        "せんげつ",
        "せんしゅう",
        "せんせい",
        "せんたく",
        "ぜんぶ",
        "そうじする",
        "そうして/そして",
        "そこ",
        "そちら",
        "そっち",
        "そと",
        "その",
        "そば",
        "そら",
        "それ",
        "それから",
        "それでは",
        "だいがく",
        "たいしかん",
        "だいじょうぶ",
        "だいすき",
        "たいせつ",
        "だいどころ",
        "たいへん",
        "たいへん",
        "たかい",
        "たくさん",
        "タクシー",
        "だす",
        "たつ",
        "たて",
        "たてもの",
        "たのしい",
        "たのむ",
        "たばこ",
        "たぶん",
        "たべもの",
        "たべる",
        "たまご",
        "だれ",
        "だれか",
        "たんじょうび",
        "だんだん",
        "ちいさい",
        "ちいさな",
        "ちかい",
        "ちがう",
        "ちかく",
        "ちかてつ",
        "ちず",
        "ちゃいろ",
        "ちゃわん",
        "ちょうど",
        "ちょっと",
        "ついたち",
        "つかう",
        "つかれる",
        "つぎ",
        "つく",
        "つくえ",
        "つくる",
        "つける",
        "つとめる",
        "つまらない",
        "つめたい",
        "つよい",
        "て",
        "テープ",
        "テーブル",
        "テープレコーダー",
        "でかける",
        "てがみ",
        "できる",
        "でぐち",
        "テスト",
        "では",
        "デパート",
        "でも",
        "でる",
        "テレビ",
        "てんき",
        "でんき",
        "でんしゃ",
        "でんわ",
        "と",
        "ドア",
        "トイレ",
        "どう",
        "どうして",
        "どうぞ",
        "どうぶつ",
        "どうも",
        "とおい",
        "とおか",
        "ときどき",
        "とけい",
        "どこ",
        "ところ",
        "とし",
        "としょかん",
        "どちら",
        "どっち",
        "とても",
        "どなた",
        "となり",
        "どの",
        "とぶ",
        "とまる",
        "ともだち",
        "どようび",
        "とり",
        "とりにく",
        "とる",
        "とる",
        "どれ",
        "ナイフ",
        "なか",
        "ながい",
        "なく",
        "なくす",
        "なぜ",
        "なつ",
        "なつやすみ",
        "など",
        "ななつ",
        "なのか",
        "なまえ",
        "ならう",
        "ならぶ",
        "ならべる",
        "なる",
        "なん/なに",
        "に",
        "にぎやか",
        "にく",
        "にし",
        "にちようび",
        "にもつ",
        "ニュース",
        "にわ",
        "ぬぐ",
        "ぬるい",
        "ネクタイ",
        "ねこ",
        "ねる",
        "ノート",
        "のぼる",
        "のみもの",
        "のむ",
        "のる",
        "は",
        "パーティー",
        "はい",
        "はいざら",
        "はいる",
        "はがき",
        "はく",
        "はこ",
        "はし",
        "はし",
        "はじまる",
        "はじめ",
        "はじめて",
        "はしる",
        "バス",
        "バター",
        "はたち",
        "はたらく",
        "はち",
        "はつか",
        "はな",
        "はな",
        "はなし",
        "はなす",
        "はやい",
        "はやい",
        "はる",
        "はる",
        "はれ",
        "はれる",
        "はん",
        "ばん",
        "パン",
        "ハンカチ",
        "ばんごう",
        "ばんごはん",
        "はんぶん",
        "ひがし",
        "ひく",
        "ひく",
        "ひくい",
        "ひこうき",
        "ひだり",
        "ひと",
        "ひとつ",
        "ひとつき",
        "ひとり",
        "ひま",
        "ひゃく",
        "びょういん",
        "びょうき",
        "ひる",
        "ひるごはん",
        "ひろい",
        "フィルム",
        "ふうとう",
        "プール",
        "フォーク",
        "ふく",
        "ふく",
        "ふたつ",
        "ぶたにく",
        "ふたり",
        "ふつか",
        "ふとい",
        "ふゆ",
        "ふる",
        "ふるい",
        "ふろ",
        "ぶんしょう",
        "ページ",
        "へた",
        "ベッド",
        "ペット",
        "へや",
        "へん",
        "ペン",
        "べんきょうする",
        "べんり",
        "ぼうし",
        "ボールペン",
        "ほか",
        "ポケット",
        "ほしい",
        "ポスト",
        "ほそい",
        "ボタン",
        "ホテル",
        "ほん",
        "ほんだな",
        "ほんとう",
        "まいあさ",
        "まいげつ/まいつき",
        "まいしゅう",
        "まいにち",
        "まいねん/まいとし",
        "まいばん",
        "まえ",
        "まがる",
        "まずい",
        "また",
        "まだ",
        "まち",
        "まつ",
        "まっすぐ",
        "マッチ",
        "まど",
        "まるい",
        "まん",
        "まんねんひつ",
        "みがく",
        "みぎ",
        "みじかい",
        "みず",
        "みせ",
        "みせる",
        "みち",
        "みっか",
        "みっつ",
        "みどり",
        "みなさん",
        "みなみ",
        "みみ",
        "みる",
        "みんな",
        "むいか",
        "むこう",
        "むずかしい",
        "むっつ",
        "むら",
        "め",
        "メートル",
        "めがね",
        "もう",
        "もういちど",
        "もくようび",
        "もつ",
        "もっと",
        "もの",
        "もん",
        "もんだい",
        "やおや",
        "やさい",
        "やさしい",
        "やすい",
        "やすみ",
        "やすむ",
        "やっつ",
        "やま",
        "やる",
        "ゆうがた",
        "ゆうはん",
        "ゆうびんきょく",
        "ゆうべ",
        "ゆうめい",
        "ゆき",
        "ゆく",
        "ゆっくりと",
        "ようか",
        "ようふく",
        "よく",
        "よこ",
        "よっか",
        "よっつ",
        "よぶ",
        "よむ",
        "よる",
        "よわい",
        "らいげつ",
        "らいしゅう",
        "らいねん",
        "ラジオ",
        "ラジカセ / ラジオカセット",
        "りっぱ",
        "りゅうがくせい",
        "りょうしん",
        "りょうり",
        "りょこう",
        "れい",
        "れいぞうこ",
        "レコード",
        "レストラン",
        "れんしゅうする",
        "ろうか",
        "ろく",
        "ワイシャツ",
        "わかい",
        "わかる",
        "わすれる",
        "わたくし",
        "わたし",
        "わたす",
        "わたる",
        "わるい",
        "より、ほう",
        ],
    n4v = [],
    n3v = [],
    n2v = [],
    n1v = [],
    list = []   
];  

var kanji = [
    n5v = [
        "会う",
        "青",
        "青い",
        "赤",
        "赤い",
        "明い",
        "秋",
        "開く",
        "開ける",
        "上げる",
        "朝",
        "朝御飯",
        "",
        "足",
        "明日",
        "",
        "遊ぶ",
        "暖かい",
        "頭",
        "新しい",
        "",
        "暑い",
        "熱い",
        "厚い",
        "",
        "後",
        "",
        "兄",
        "姉",
        "",
        "",
        "",
        "",
        "危ない",
        "甘い",
        "",
        "雨",
        "飴",
        "洗う",
        "",
        "歩く",
        "",
        "",
        "",
        "言う",
        "家",
        "",
        "行く",
        "",
        "",
        "池",
        "医者",
        "",
        "忙しい",
        "痛い",
        "一",
        "一日",
        "",
        "",
        "五日",
        "一緒",
        "五つ",
        "",
        "犬",
        "今",
        "意味",
        "妹",
        "嫌",
        "入口",
        "居る",
        "要る",
        "入れる",
        "色",
        "",
        "上",
        "後ろ",
        "薄い",
        "歌",
        "歌う",
        "生まれる",
        "海",
        "売る",
        "煩い",
        "上着",
        "絵",
        "映画",
        "映画館",
        "英語",
        "",
        "駅",
        "",
        "鉛筆",
        "",
        "多い",
        "大きい",
        "大きな",
        "大勢",
        "お母さん",
        "お菓子",
        "お金",
        "起きる",
        "置く",
        "奥さん",
        "お酒",
        "お皿",
        "伯父/叔父",
        "教える",
        "伯父/叔父",
        "押す",
        "遅い",
        "お茶",
        "お手洗い",
        "お父さん",
        "弟",
        "男",
        "男の子",
        "一昨日",
        "一昨年",
        "大人",
        "",
        "同じ",
        "お兄さん",
        "お姉さん",
        "",
        "伯母さん/叔母さん",
        "お風呂",
        "お弁当",
        "覚える",
        "",
        "重い",
        "",
        "泳ぐ",
        "降りる",
        "終る",
        "音楽",
        "女",
        "女の子",
        "外国",
        "外国人",
        "会社",
        "階段",
        "買い物",
        "買う",
        "返す",
        "帰る",
        "",
        "",
        "書く",
        "学生",
        "",
        "傘",
        "貸す",
        "風",
        "風邪",
        "家族",
        "方",
        "学校",
        "",
        "家庭",
        "角",
        "",
        "花瓶",
        "紙",
        "",
        "火曜日",
        "辛い",
        "体",
        "借りる",
        "軽い",
        "",
        "",
        "川/河",
        "",
        "漢字",
        "木",
        "黄色",
        "黄色い",
        "消える",
        "聞く",
        "北",
        "",
        "汚い",
        "喫茶店",
        "切手",
        "切符",
        "昨日",
        "九",
        "牛肉",
        "牛乳",
        "今日",
        "教室",
        "兄弟",
        "去年",
        "嫌い",
        "切る",
        "着る",
        "",
        "",
        "",
        "銀行",
        "金曜日",
        "薬",
        "",
        "果物",
        "口",
        "靴",
        "靴下",
        "国",
        "曇り",
        "曇る",
        "暗い",
        "",
        "",
        "来る",
        "車",
        "黒",
        "黒い",
        "警官",
        "今朝",
        "消す",
        "結構",
        "結婚",
        "月曜日",
        "玄関",
        "元気",
        "五",
        "公園",
        "交差点",
        "紅茶",
        "交番",
        "声",
        "",
        "",
        "",
        "午後",
        "九日",
        "九つ",
        "午前",
        "答える",
        "",
        "",
        "",
        "今年",
        "言葉",
        "子供",
        "",
        "御飯",
        "",
        "困る",
        "",
        "今月",
        "今週",
        "",
        "今晩",
        "",
        "財布",
        "魚",
        "先",
        "咲く",
        "作文",
        "差す",
        "雑誌",
        "砂糖",
        "寒い",
        "さ来年",
        "三",
        "散歩",
        "四",
        "塩",
        "",
        "時間",
        "仕事",
        "辞書",
        "静か",
        "下",
        "七",
        "質問",
        "自転車",
        "自動車",
        "死ぬ",
        "字引",
        "自分",
        "閉まる",
        "閉める",
        "締める",
        "",
        "写真",
        "",
        "",
        "十",
        "授業",
        "宿題",
        "上手",
        "丈夫",
        "",
        "食堂",
        "知る",
        "白",
        "白い",
        "新聞",
        "水曜日",
        "吸う",
        "",
        "好き",
        "少ない",
        "",
        "少し",
        "涼しい",
        "",
        "",
        "",
        "",
        "住む",
        "",
        "",
        "座る",
        "背",
        "生徒",
        "",
        "",
        "背広",
        "狭い",
        "",
        "千",
        "先月",
        "先週",
        "先生",
        "洗濯",
        "全部",
        "掃除",
        "",
        "",
        "",
        "",
        "外",
        "",
        "",
        "空",
        "",
        "",
        "",
        "大学",
        "大使館",
        "大丈夫",
        "大好き",
        "大切",
        "台所",
        "",
        "",
        "高い",
        "",
        "",
        "出す",
        "立つ",
        "",
        "建物",
        "楽しい",
        "頼む",
        "",
        "",
        "食べ物",
        "食べる",
        "卵",
        "誰",
        "誰",
        "誕生日",
        "",
        "小さい",
        "小さな",
        "近い",
        "違う",
        "近く",
        "地下鉄",
        "地図",
        "茶色",
        "",
        "",
        "",
        "一日",
        "使う",
        "疲れる",
        "次",
        "着く",
        "机",
        "作る",
        "",
        "勤める",
        "",
        "冷たい",
        "強い",
        "手",
        "",
        "",
        "",
        "出かける",
        "手紙",
        "",
        "出口",
        "",
        "",
        "",
        "",
        "出る",
        "",
        "天気",
        "電気",
        "電車",
        "電話",
        "戸",
        "",
        "",
        "",
        "",
        "",
        "動物",
        "",
        "遠い",
        "十日",
        "時々",
        "時計",
        "",
        "所",
        "年",
        "図書館",
        "",
        "",
        "",
        "",
        "隣",
        "",
        "飛ぶ",
        "止まる",
        "友達",
        "土曜日",
        "鳥",
        "とり肉",
        "取る",
        "撮る",
        "",
        "",
        "中",
        "長い",
        "鳴く",
        "無くす",
        "",
        "夏",
        "夏休み",
        "",
        "七つ",
        "七日",
        "名前",
        "習う",
        "並ぶ",
        "並べる",
        "",
        "何",
        "二",
        "賑やか",
        "肉",
        "西",
        "日曜日",
        "荷物",
        "",
        "庭",
        "脱ぐ",
        "温い",
        "",
        "猫",
        "寝る",
        "",
        "登る",
        "飲み物",
        "飲む",
        "乗る",
        "歯",
        "",
        "",
        "灰皿",
        "入る",
        "葉書",
        "",
        "箱",
        "橋",
        "",
        "始まる",
        "初め/始め",
        "初めて",
        "走る",
        "",
        "",
        "二十歳",
        "働く",
        "八",
        "二十日",
        "花",
        "鼻",
        "話",
        "話す",
        "早い",
        "速い",
        "春",
        "貼る",
        "晴れ",
        "晴れる",
        "半",
        "晩",
        "",
        "",
        "番号",
        "晩御飯",
        "半分",
        "東",
        "引く",
        "弾く",
        "低い",
        "飛行機",
        "左",
        "人",
        "一つ",
        "一月",
        "一人",
        "暇",
        "百",
        "病院",
        "病気",
        "昼",
        "昼御飯",
        "広い",
        "",
        "封筒",
        "",
        "",
        "吹く",
        "服",
        "二つ",
        "豚肉",
        "二人",
        "二日",
        "太い",
        "冬",
        "降る",
        "古い",
        "",
        "文章",
        "",
        "下手",
        "",
        "",
        "部屋",
        "辺",
        "",
        "勉強",
        "便利",
        "帽子",
        "",
        "",
        "",
        "欲しい",
        "",
        "細い",
        "",
        "",
        "本",
        "本棚",
        "",
        "毎朝",
        "毎月",
        "毎週",
        "毎日",
        "毎年",
        "毎晩",
        "前",
        "曲る",
        "",
        "",
        "",
        "町",
        "待つ",
        "",
        "",
        "窓",
        "丸い/円い",
        "万",
        "万年筆",
        "磨く",
        "右",
        "短い",
        "水",
        "店",
        "見せる",
        "道",
        "三日",
        "三つ",
        "緑",
        "皆さん",
        "南",
        "耳",
        "見る 観る",
        "",
        "六日",
        "向こう",
        "難しい",
        "六つ",
        "村",
        "目",
        "",
        "眼鏡",
        "",
        "もう一度",
        "木曜日",
        "持つ",
        "",
        "物",
        "門",
        "問題",
        "八百屋",
        "野菜",
        "易しい",
        "安い",
        "休み",
        "休む",
        "八つ",
        "山",
        "",
        "夕方",
        "夕飯",
        "郵便局",
        "昨夜",
        "有名",
        "雪",
        "行く",
        "",
        "八日",
        "洋服",
        "",
        "横",
        "四日",
        "四つ",
        "呼ぶ",
        "読む",
        "夜",
        "弱い",
        "来月",
        "来週",
        "来年",
        "",
        "",
        "",
        "留学生",
        "両親",
        "料理",
        "旅行",
        "零",
        "冷蔵庫",
        "",
        "",
        "練習",
        "廊下",
        "六",
        "",
        "若い",
        "分かる",
        "忘れる",
        "私",
        "私",
        "渡す",
        "渡る",
        "悪い",
        "",
        ],
    n4v = [],
    n3v = [],
    n2v = [],
    n1v = [],
    list = []     
];


var answer;
var i = 0;
var n = 0;
var m = 0;
var executed = false;
var iHidHiragana = false;
var showHiragana = true;

var INIT = (function() {
    return function() {
        if (!executed) {
            if(Cookies.get('vkanjiList') != undefined && Cookies.get('veigoList') != undefined && Cookies.get('vhiraganaList') != undefined) {
                var listKanji = JSON.parse(Cookies.get('vkanjiList'));
                kanji[5]  = listKanji;
                var listEigo = JSON.parse(Cookies.get('veigoList'));
                eigo[5]  = listEigo;
                var listHiragana = JSON.parse(Cookies.get('vhiraganaList'));
                hiragana[5]  = listHiragana;
                $(".list").attr('disabled', false);
            }
            $(".kanji").text(kanji[n][i]);
            $(".eigo").text(eigo[n][i]);
            $(".hiragana").text(hiragana[n][i]);
            $(".count").text(i+"/"+eigo[n].length)
            executed = true;
        }
    };
})();

INIT(); // Initializes first kanji of N5

function simulateEnter () {
    e = jQuery.Event("keypress")
    e.which = 13 //choose the one you want
    $(".count").text(i+"/"+eigo[n].length)
    $(document).keypress(function(){
    }).trigger(e) 
    
}

function difficulty() {
    i=0;
    n = $('#select[name=diff]:checked').val();
    simulateEnter();
}

function options() {
    $(".options").slideToggle("fast");
}

$(".fonts").change(function() {
    var str = "";
    $( ".fonts option:selected" ).each(function() {
      str = $(this).val();
    });
    $(".kanji").css("font-family", ('"'+str+'"'))
})

//Fisher-Yates Shuffle
function shuffle(a, b, c) {
    for (let m = a.length - 1; m > 0; m--) {
        const j = Math.floor(Math.random() * (m + 1));
        [a[m], a[j]] = [a[j], a[m]];
        [b[m], b[j]] = [b[j], b[m]];
        [c[m], c[j]] = [c[j], c[m]];
    }
    i=0;
    simulateEnter(); 
    return a, b, c;
}

//Take 10 steps back
function repeatMinus() {
    i-=5;
    if(i<0) {
        i=0;
    }
    simulateEnter();
}

//Take 10 steps forward
function repeatPlus() {
    i+=5;
    if(i >= eigo[n].length) {
        i=0;
    }
    simulateEnter();
}

var keys = {};
var timerStart = 0;
//Whats happens when you press enter
$(document).keyup(function(e) {
    if(e.which == 13){
        
        $(".kanji").css("color", "black")
        $(".hiragana").css("color", "black")
        answer = $("input").val().toLowerCase();
        $(".eigo").css("visibility", "hidden");
        $(".kanji").text(kanji[n][i]);
        $(".hiragana").text(hiragana[n][i]);
        $(".eigo").text(eigo[n][i]);
        e_val = $(".eigo").text(eigo[n][i]+ " | " + hiragana[n][i]).text().toLowerCase();
        e_eval_h = $(".hiragana").text(hiragana[n][i]).text();
        
        
        if (i===eigo[n].length) {
            $(".kanji").text(kanji[n][0]);
            $(".eigo").text(eigo[n][0] + " | " + hiragana[n][i]);
            $(".hiragana").text(hiragana[n][0]);
            i=0;
           
        }
        
        if (e_val.includes(answer) === true && answer!="" && answer!=undefined || e_eval_h.includes(answer) === true && answer!="" && answer!=undefined ) {
            $(".kanji").animate({color: "#5CDBA4"},200);
            $(".hiragana").animate({color: "#5CDBA4"},200);
            $(".action").val("")
            $(".eigo").css("visibility", "visible");
            i++; 
            
            $(".count").text(i+"/"+eigo[n].length)
            timerStart++;
            if(timerStart == 1 && timerShow == true) {
                timer();
            }
            if(i == eigo[n].length - 1) {
                clearTimeout(t);
            }
            
            m++; 
            }  
            console.log(m)
        }
        
        
        if(kanji[n][i] === "" && showHiragana === false && iHidHiragana === false && m==0) {
            console.log("a")
            console.log(m)
            console.log(showHiragana)
            $(".hiragana").css("visibility", "visible")
            iHidHiragana = true;
            console.log(iHidHiragana)
      

        }
        
        if(kanji[n][i] !== "" && iHidHiragana === true && m==0) {
            console.log("b")
            $(".hiragana").css("visibility", "hidden")
            iHidHiragana = false;
            console.log(m)
            console.log(showHiragana)
            console.log(iHidHiragana)
           
            

        }
        if(m === 1)
        m=0

        
    if (e.which == 37) {
        repeatMinus();
    }

    if (e.which == 39) {
        repeatPlus();
    }

    if (e.which == 38) {
        hideHiragana();
    }
    if (e.which == 40) {
        addToList();
    }
    
});

function addToList () {
    if($.inArray(kanji[n][i],kanji[5]) == -1 ) {
        kanji[5].push(kanji[n][i]);
        eigo[5].push(eigo[n][i]);
        hiragana[5].push(hiragana[n][i]);
        Cookies.set('vkanjiList', kanji[5], { expires: 7, path: '/' });
        Cookies.set('veigoList', eigo[5], { expires: 7, path: '/' });
        Cookies.set('vhiraganaList', hiragana[5], { expires: 7, path: '/' });
        $(".list").attr('disabled', false);
    } else {
        console.log("already added "+ kanji[n][i]);
    }
};

function removeList() {
    if (confirm("Are you sure you want to remove the list?")) {
        Cookies.remove('vkanjiList');
        Cookies.remove('veigoList');
        Cookies.remove('vhiraganaList');
        location.reload();
    }
}


function hideHiragana() {
    showHiragana = !showHiragana
    iHidHiragana = false;
    if(showHiragana) {
        $(".hiragana").css("visibility", "visible")
    }else{
        $(".hiragana").css("visibility", "hidden")
    }
}



//if(iHidHiragana)


$(".peek").mouseover( function() {
    $(".peek").text(eigo[n][i] + " | " + hiragana[n][i]);

}); 

$( ".peek" ).mouseenter(function() {
    $(".peek").text(eigo[n][i] + " | " + hiragana[n][i]);
  }).mouseleave(function() {
    $(".peek").text("Hover to cheat...");
  });


//stopwatch

var p = document.getElementsByTagName('p')[0],
    seconds = 0, minutes = 0, hours = 0,
    t;

function add() {
    seconds++;
    if (seconds >= 60) {
        seconds = 0;
        minutes++;
        if (minutes >= 60) {
            minutes = 0;
            hours++;
        }
    }
    
    p.textContent = (hours ? (hours > 9 ? hours : "0" + hours) : "00") + ":" + (minutes ? (minutes > 9 ? minutes : "0" + minutes) : "00") + ":" + (seconds > 9 ? seconds : "0" + seconds);
    timer();
}
function timer() {
    t = setTimeout(add, 1000);
}

var timerShow = false;

function showTimer() {
    timerShow = !timerShow;
    if(timerShow) {
        $(".timer").css("visibility", "visible");
    }
    else {
        clearTimeout(t);
        $(".timer").css("visibility", "hidden");
        p.textContent = "00:00:00";
        seconds = 0; minutes = 0; hours = 0;
        timerStart = 0;
    }
    
}




/* Stop button 
stop.onclick = function() {
    clearTimeout(t);
}

/* Clear button 
clear.onclick = function() {
    p.textContent = "00:00:00";
    seconds = 0; minutes = 0; hours = 0;
}

*/   


    

    



    
    




